Cambio en el texto para ver nuevas opciones de Reviewers
opas350/gitTraining_First pull request #2
Opened 2018-04-16 20:39 UTC by Juan12345Ledezma

2018-04-16 20:52 UTC, Juan12345Ledezma reviewed
Creo que no me deja añadir Reviewers Javi.

2018-04-16 20:53 UTC, Juan12345Ledezma commented
Creo que no me deja añadir Reviewers

2018-04-18 19:31 UTC, opas350 commented on Juan/example1/Example1.java
Mover esto abajo

2018-04-18 19:32 UTC, opas350 requested changes
Needs work

2018-04-18 19:32 UTC, merged